In [1]:
import numpy as np

## 1-D Array with Numpy

In [2]:
mylist = [1,2,3,4]
ar = np.array(mylist)
print(ar)
print(type(ar))
print(ar.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


## 2-D Array with Numpy

In [3]:
ar2d = [[1,2],[2,3]]
ar2d = np.array(ar2d)
print(ar2d)
print(type(ar2d))
print(ar2d.shape)

[[1 2]
 [2 3]]
<class 'numpy.ndarray'>
(2, 2)


## Reshaping Arrays with Numpy

In [4]:
arr = [[1,2,3,4,5,6],[1,6,7,8,9,5],[5,8,5,2,6,4]]
arr = np.array(arr)
print(arr)

[[1 2 3 4 5 6]
 [1 6 7 8 9 5]
 [5 8 5 2 6 4]]


In [5]:
arr.shape

(3, 6)

In [6]:
arr.reshape(2,9)

array([[1, 2, 3, 4, 5, 6, 1, 6, 7],
       [8, 9, 5, 5, 8, 5, 2, 6, 4]])

## Subarrays from arrays 

In [7]:
arr[1:2, 1:4]

array([[6, 7, 8]])

In [8]:
arr[1:3, 3:5]

array([[8, 9],
       [2, 6]])

## Some useful conditions in Exploratory Data Analysis 

In [9]:
ar = [1,2,3,4,5,6,7,8,9]
ar = np.array(ar)

In [10]:
print(ar < 5)

[ True  True  True  True False False False False False]


In [11]:
print(ar * 5)

[ 5 10 15 20 25 30 35 40 45]
